import React, { createContext, useState, useContext, useEffect } from 'react';

const AppContext = createContext();

export const AppProvider = ({ children }) => {
  // Theme state
  const [theme, setTheme] = useState('light'); // Default to light

  // Language state (default 'vi')
  const [language, setLanguage] = useState('vi');

  // Translations
  const translations = {
    en: {
      services: 'Services',
      projects: 'Projects',
      news: 'News',
      contact: 'Contact',
      quote: 'Quote',
      getStarted: 'Consult Now',
      companyName: 'VIT DIGITAL TRADING SERVICE CO., LTD',
      // Contact Section
      getInTouch: 'Get in Touch',
      startProject: "Let's Start a Project Together",
      contactDesc: 'Ready to take your digital presence to the next level? Contact us today for a free consultation.',
      ourOffice: 'Our Office',
      phone: 'Phone',
      email: 'Email',
      fullName: 'Full Name',
      emailAddress: 'Email Address',
      subject: 'Service',
      selectSubject: 'Select a service',
      phoneNumber: 'Phone Number',
      jobTitle: 'Job Title',
      selectJobTitle: 'Select your role',
      message: 'Message',
      sendMessage: 'Send Message',

      messageSent: 'Thank you! Your message has been sent.',
      phName: 'John Doe',
      phEmail: 'john@example.com',
      phPhone: '0912 345 678',
      phMessage: 'Tell us about your project...',
      // Footer
      quickLinks: 'Quick Links',
      aboutUs: 'About Us',
      careers: 'Careers',
      // Services Section Summary
      whatWeDo: 'What We Do',
      premiumServices: 'Our Premium Services',
      // Service Page Template
      heroBtnProcess: 'View Process',
      painPointsTitle: 'Are you facing these issues?',
      painPointsDesc: "Don't let these barriers hold your business back.",
      solutionsTitle: 'Our Solutions',
      solutionsDesc: 'Comprehensive optimization strategies to help you break through.',
      processTitle: 'Working Process',
      processDesc: 'Transparent, clear, and effective.',
      whyChooseUs: 'Why Choose VIT DIGITAL?',
      realResults: 'Real Results',
      realResultsDesc: 'Clear KPI commitment, transparent 24/7 reporting.',
      expertTeam: 'Expert Team',
      expertTeamDesc: 'Personnel with >5 years of practical multi-industry experience.',
      speedFlexibility: 'Speed & Flexibility',
      speedFlexibilityDesc: 'Rapid deployment, continuous optimization according to the market.',
      supportHotline: 'Support Hotline 24/7',
      // Hero Section
      heroTag: 'DIGITAL AGENCY',
      heroTitle1: 'Elevate',
      heroTitle2: 'Digital Brand',
      heroDesc: 'We create impressive digital experiences. From comprehensive marketing strategies to high-class website design, turning your vision into reality.',
      heroConsult: 'Get Consultation',
      heroViewProjects: 'View Projects',
      heroPremium: 'PREMIUM QUALITY',
      heroStrategy: 'Strategy & Creative',
      heroROI: 'ROI Growth',
      heroSatisfaction: 'Satisfied Clients',
      // Services Section Main
      ourServices: 'Our Services',
      compSolutions: 'Comprehensive Solutions',
      servicesSub: 'We provide digital marketing solutions tailored to each business, ensuring optimal efficiency and sustainable growth.',
      viewDetails: 'View Details',
      // Service Items (Main Page)
      svcMarketing: 'Overall Marketing',
      svcMarketingDesc: 'Comprehensive strategy, optimizing every touchpoint for sustainable revenue growth.',
      svcStrategy: 'Strategic Consulting',
      svcStrategyDesc: 'Clear direction, building specific action plans for each development stage.',
      svcAds: 'Ads Services',
      svcAdsDesc: 'Optimize budget, reach the right target audience on Facebook, Google, TikTok.',
      svcSEO: 'Comprehensive SEO',
      svcSEODesc: 'Sustainable Google top ranking, increasing organic traffic for the website.',
      svcTikTok: 'TikTok Marketing',
      svcTikTokDesc: 'Viral content creation and channel growth, catching short video trends.',
      srvLive: 'Livestream & TikTok Studio',
      srvLiveDesc: 'Scripts, MC, professional live room setup.',
      svcWeb: 'Website Design',
      svcWebDesc: 'SEO-standard website, modern interface, fast loading speed.',
      // Blog Section
      latestNews: 'Latest News',
      insights: 'Insights & Knowledge',
      viewAllPosts: 'View All Posts',
      readMore: 'Read More',
      // Footer/General
      companyAddress: '123 Business Avenue, Tech District, HCM City, Vietnam',
      companyPhone: '0966 290 789',
      companyEmail: 'hello@vitdigital.vn',
      newsletterTitle: 'Newsletter',
      subscribeBtn: 'Subscribe',
      emailPlaceholder: 'Email address',
      chatZalo: 'Chat Zalo',
      callNow: 'Call Now',
      companyLabel: 'Company',
      // Footer/General
      privacyPolicy: 'Privacy Policy',
      termsOfService: 'Terms of Service',
      subscribeNewsletter: 'Subscribe to our newsletter for the latest updates.',
      // Pricing
      pricingTitle: 'Optimal Solutions – Effective Cost',
      pricingSubtitle: 'We provide flexible service packages tailored to your business budget and growth goals.',
      pkgStartup: 'Startup Package',
      pkgStartupDesc: 'For new businesses, focusing on building a professional basic brand presence.',
      pkgGrowth: 'Growth Package',
      pkgGrowthDesc: 'Most popular. Focus on sales growth and rapid market expansion.',
      pkgEnterprise: 'Enterprise Package',
      pkgEnterpriseDesc: 'Comprehensive, custom-tailored solutions for corporations and large enterprises.',
      mostPopular: 'Most Popular',
      registerNow: 'Register Now',
      contactForPrice: 'Contact Us',
      perMonth: '/month',
      detailedServices: 'Detailed Services',
      detailedServicesDesc: 'Specialized standalone solutions for specific needs',
      srvAds: 'Ads (FB/Google/TikTok)',
      srvAdsDesc: 'Optimize conversion costs, target the right audience.',
      srvSEO: 'Comprehensive SEO',
      srvSEODesc: 'Sustainable top ranking, covering thousands of industry keywords.',
      srvEcom: 'E-commerce Operation',
      srvEcomDesc: 'Shopee, Lazada, TikTok Shop. Store & sales optimization.',
      srvWeb: 'Website & App Design',
      srvWebDesc: 'Modern UI/UX, SEO standard, high speed.',
      srvContent: 'Content Marketing',
      srvContentDesc: 'Create viral content, manage fanpages/websites.',
      quoteTitle: 'Get a Quote',
      quoteDesc: 'Fill in the form, our experts will analyze and send you a detailed quote within 24h.',
      quoteSecurity: '100% Information Security',
      quoteResponse: 'Fast Response',
      quoteConsult: 'Free Consultation',
      budget: 'Estimated Budget',
      interestedService: 'Service of Interest',
      btnQuote: 'Request Quote (Free)',
      faqTitle: 'Frequently Asked Questions',
      // FAQ Questions (Simplification for generic keys, ideally dynamic but hardcoded for now)
      faq1: 'Are there any extra costs during implementation?',
      faq1a: 'We commit to a package cost as per the contract. Any additional costs (e.g., increasing ad budget) are notified and agreed upon in writing.',
      faq2: 'Does ZMarketing commit to KPIs?',
      faq2a: 'Yes. We work based on real data. KPIs (Reach, Engagement, Conversion, Revenue...) are clearly committed in the contract.',
      faq3: 'What is the minimum contract duration?',
      faq3a: 'To ensure effectiveness (especially SEO or Branding), we recommend 3-6 months. However, we also have trial or short-term packages.',
      faq4: 'Can I change the service package mid-term?',
      faq4a: 'Absolutely. We flexibly adjust plans to best suit your business situation at any time.',
      // Work Process
      workingProcess: 'Working Process',
      step1: 'Receive Request',
      step1Desc: 'Listen to business needs and goals.',
      step2: 'Survey & Analyze',
      step2Desc: 'Research market, competitors, and internal status.',
      step3: 'Propose Solution',
      step3Desc: 'Detailed planning and budget optimization.',
      step4: 'Sign & Deploy',
      step4Desc: 'KPI commitment and transparent reporting.',
      // Portfolio
      ourWork: 'Our Work',
      featuredProjects: 'Featured Projects',
      viewProject: 'View Project',
      // Form Options
      jobOwner: 'Business Owner / CEO',
      jobManager: 'Manager / Head of Dept',
      jobMarketer: 'Marketing Staff',
      jobFreelancer: 'Freelancer',
      jobOther: 'Other',
      subjMarketing: 'Overall Marketing',
      subjStrategy: 'Strategic Consulting',
      subjAds: 'Ads Services (FB/Google/TikTok)',
      subjSEO: 'Comprehensive SEO',
      subjTikTok: 'TikTok Marketing / Livestream',
      subjWeb: 'Website Design',
      subjOther: 'Other',
      budgetU20: 'Under 20 million',
      budget20_50: '20 - 50 million',
      budget50_100: '50 - 100 million',
      budgetO100: 'Over 100 million',
      // Pricing Features (Startup)
      ftS1: 'Fanpage Management: 8 posts/month',
      ftS2: 'Basic Image Design',
      ftS3: 'Basic Facebook Ads Setup',
      ftS4: 'Monthly Performance Report',
      ftS5: 'Zalo Group Support',
      // Pricing Features (Growth)
      ftG1: 'Fanpage & Website Mgt: 15 posts/month',
      ftG2: 'Basic Image & Short Video Design',
      ftG3: 'Advanced Multi-channel Ads (FB, Google)',
      ftG4: 'Basic SEO Optimization',
      ftG5: 'Group & Forum Seeding',
      ftG6: 'Detailed Weekly & Monthly Reports',
      // Pricing Features (Enterprise)
      ftE1: 'Overall Multi-channel Marketing Strategy',
      ftE2: 'Professional TVC & Viral Video Production',
      ftE3: 'Booking KOLs/Influencers',
      ftE4: 'Event Organization & Brand Activation',
      ftE5: 'Media Crisis Management',
      ftE6: 'Dedicated In-house Team',
      // Why Choose Us
      wcuTitle: 'Why Choose VIT DIGITAL?',
      wcuSubtitle: 'Optimizing Growth Strategies',
      wcuPartner: 'Trusted Partner For',
      wcuGrowth: 'Your Growth',
      wcuDesc: 'We are not just a service provider, but a strategic partner helping you solve revenue and branding challenges.',
      wcuSecurity: 'Security & Safety',
      wcuSecurityDesc: 'Commitment to absolute customer data security according to international standards.',
      wcuKPI: 'KPI Commitment',
      wcuKPICommit: 'Refund if committed efficiency is not achieved.',
    },
    vi: {
      services: 'Dịch vụ',
      projects: 'Dự án',
      news: 'Tin tức',
      contact: 'Liên hệ',
      quote: 'Báo giá',
      getStarted: 'Tư vấn ngay',
      companyName: 'CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ VIT DIGITAL',
      // Contact Section
      getInTouch: 'Liên hệ',
      startProject: 'Bắt đầu dự án cùng chúng tôi',
      contactDesc: 'Sẵn sàng nâng tầm sự hiện diện số của bạn? Liên hệ ngay hôm nay để được tư vấn miễn phí.',
      ourOffice: 'Văn phòng',
      phone: 'Điện thoại',
      email: 'Email',
      fullName: 'Họ và tên',
      emailAddress: 'Địa chỉ Email',
      subject: 'Dịch vụ cần tư vấn',
      selectSubject: 'Chọn dịch vụ',
      phoneNumber: 'Số điện thoại',
      jobTitle: 'Nghề nghiệp/Chức vụ',
      selectJobTitle: 'Chọn chức vụ của bạn',
      message: 'Nội dung',
      sendMessage: 'Gửi tin nhắn',

      messageSent: 'Cảm ơn! Tin nhắn của bạn đã được gửi.',
      phName: 'Nguyễn Văn A',
      phEmail: 'email@example.com',
      phPhone: '0912 345 678',
      phMessage: 'Hãy chia sẻ về dự án của bạn...',
      // Footer
      quickLinks: 'Liên kết nhanh',
      aboutUs: 'Về chúng tôi',
      careers: 'Tuyển dụng',
      // Services Section Summary
      whatWeDo: 'Chúng tôi làm gì',
      premiumServices: 'Dịch vụ cao cấp',
      // Service Page Template
      heroBtnProcess: 'Xem quy trình',
      painPointsTitle: 'Bạn đang gặp vấn đề?',
      painPointsDesc: 'Đừng để những rào cản này kìm hãm sự phát triển của doanh nghiệp bạn.',
      solutionsTitle: 'Giải pháp của chúng tôi',
      solutionsDesc: 'Chiến lược tối ưu hóa toàn diện giúp bạn bứt phá.',
      processTitle: 'Quy trình làm việc',
      processDesc: 'Minh bạch, rõ ràng và hiệu quả.',
      whyChooseUs: 'Tại sao chọn VIT DIGITAL?',
      realResults: 'Hiệu quả thực tế',
      realResultsDesc: 'Cam kết KPI rõ ràng, báo cáo minh bạch 24/7.',
      expertTeam: 'Đội ngũ chuyên gia',
      expertTeamDesc: 'Nhân sự hơn 5 năm kinh nghiệm thực chiến đa ngành.',
      speedFlexibility: 'Tốc độ & Linh hoạt',
      speedFlexibilityDesc: 'Triển khai nhanh chóng, tối ưu liên tục theo thị trường.',
      supportHotline: 'Hotline hỗ trợ 24/7',
      // Hero Section
      heroTag: 'DIGITAL AGENCY',
      heroTitle1: 'Nâng Tầm',
      heroTitle2: 'Thương Hiệu Số',
      heroDesc: 'Chúng tôi kiến tạo trải nghiệm số ấn tượng. Từ chiến lược marketing tổng thể đến thiết kế website đẳng cấp, biến tầm nhìn của bạn thành hiện thực.',
      heroConsult: 'Nhận Tư Vấn',
      heroViewProjects: 'Xem Dự Án',
      heroPremium: 'CHẤT LƯỢNG CAO CẤP',
      heroStrategy: 'Chiến Lược & Sáng Tạo',
      heroROI: 'Tăng Trưởng ROI',
      heroSatisfaction: 'Khách Hàng Hài Lòng',
      // Services Section Main
      ourServices: 'Dịch Vụ Của Chúng Tôi',
      compSolutions: 'Giải Pháp Toàn Diện',
      servicesSub: 'Chúng tôi cung cấp các giải pháp marketing số được may đo riêng cho từng doanh nghiệp, đảm bảo hiệu quả tối ưu và tăng trưởng bền vững.',
      viewDetails: 'Xem chi tiết',
      // Service Items (Main Page)
      svcMarketing: 'Marketing Tổng Thể',
      svcMarketingDesc: 'Chiến lược toàn diện, tối ưu hóa mọi điểm chạm để tăng trưởng doanh thu bền vững.',
      svcStrategy: 'Tư Vấn Chiến Lược',
      svcStrategyDesc: 'Định hướng rõ ràng, xây dựng kế hoạch hành động cụ thể cho từng giai đoạn phát triển.',
      svcAds: 'Dịch Vụ Quảng Cáo',
      svcAdsDesc: 'Tối ưu ngân sách, tiếp cận đúng khách hàng mục tiêu trên Facebook, Google, TikTok.',
      svcSEO: 'SEO Tổng Thể',
      svcSEODesc: 'Lên top Google bền vững, gia tăng lưu lượng truy cập tự nhiên cho website.',
      svcTikTok: 'TikTok Marketing',
      svcTikTokDesc: 'Xây kênh viral, quảng cáo chuyển đổi, nắm bắt xu hướng video ngắn.',
      srvLive: 'Livestream & TikTok Studio',
      srvLiveDesc: 'Kịch bản, MC, setup phòng live chuyên nghiệp.',
      svcWeb: 'Thiết Kế Website',
      svcWebDesc: 'Website chuẩn SEO, giao diện hiện đại, tốc độ tải trang nhanh chóng.',
      // Blog Section
      latestNews: 'Tin Tức Mới Nhất',
      insights: 'Góc Nhìn & Kiến Thức',
      viewAllPosts: 'Xem Tất Cả Bài Viết',
      readMore: 'Đọc Thêm',
      // Footer/General
      companyAddress: '123 Business Avenue, Tech District, TP.HCM, Việt Nam',
      companyPhone: '0966 290 789',
      companyEmail: 'hello@vitdigital.vn',
      newsletterTitle: 'Bản Tin',
      subscribeBtn: 'Đăng Ký',
      emailPlaceholder: 'Địa chỉ Email',
      chatZalo: 'Chat Zalo',
      callNow: 'Gọi Ngay',
      companyLabel: 'Công ty',
      privacyPolicy: 'Chính sách bảo mật',
      termsOfService: 'Điều khoản dịch vụ',
      subscribeNewsletter: 'Đăng ký nhận bản tin để cập nhật những tin tức mới nhất.',
      // Pricing
      pricingTitle: 'Giải Pháp Tối Ưu – Chi Phí Hiệu Quả',
      pricingSubtitle: 'Chúng tôi cung cấp các gói dịch vụ linh hoạt, được thiết kế riêng để phù hợp với ngân sách và mục tiêu tăng trưởng của từng doanh nghiệp.',
      pkgStartup: 'Gói Startup',
      pkgStartupDesc: 'Dành cho doanh nghiệp mới, tập trung vào xây dựng hiện diện thương hiệu cơ bản chuyên nghiệp.',
      pkgGrowth: 'Gói Growth',
      pkgGrowthDesc: 'Gói phổ biến nhất. Tập trung tăng trưởng doanh số và mở rộng thị phần nhanh chóng.',
      pkgEnterprise: 'Gói Enterprise',
      pkgEnterpriseDesc: 'Giải pháp toàn diện, may đo riêng cho các tập đoàn và doanh nghiệp lớn.',
      mostPopular: 'Phổ biến nhất',
      registerNow: 'Đăng ký ngay',
      contactForPrice: 'Liên hệ',
      perMonth: '/tháng',
      detailedServices: 'Dịch Vụ Chi Tiết',
      detailedServicesDesc: 'Các giải pháp đơn lẻ phục vụ nhu cầu chuyên biệt',
      srvAds: 'Quảng cáo FB/Google/TikTok',
      srvAdsDesc: 'Tối ưu chi phí chuyển đổi, target đúng đối tượng tiềm năng.',
      srvSEO: 'SEO Tổng Thể',
      srvSEODesc: 'Lên top bền vững, phủ sóng hàng ngàn từ khóa ngành.',
      srvEcom: 'Vận hành sàn TMĐT',
      srvEcomDesc: 'Shopee, Lazada, TikTok Shop. Tối ưu gian hàng & doanh số.',
      srvWeb: 'Thiết kế Website & App',
      srvWebDesc: 'UI/UX hiện đại, chuẩn SEO, tốc độ cao.',
      srvContent: 'Content Marketing',
      srvContentDesc: 'Sáng tạo nội dung viral, chăm sóc fanpage/website.',
      quoteTitle: 'Liên Hệ Nhận Báo Giá',
      quoteDesc: 'Điền thông tin vào form bên cạnh, chuyên gia của chúng tôi sẽ phân tích và gửi báo giá chi tiết phù hợp nhất cho bạn trong vòng 24h.',
      quoteSecurity: 'Bảo mật thông tin 100%',
      quoteResponse: 'Phản hồi nhanh chóng',
      quoteConsult: 'Tư vấn miễn phí',
      budget: 'Ngân sách dự kiến',
      interestedService: 'Dịch vụ quan tâm',
      btnQuote: 'Gửi yêu cầu nhận báo giá (Miễn phí)',
      faqTitle: 'Câu Hỏi Thường Gặp',
      faq1: 'Chi phí có phát sinh trong quá trình triển khai không?',
      faq1a: 'Chúng tôi cam kết chi phí trọn gói theo hợp đồng. Mọi chi phí phát sinh (nếu có, ví dụ tăng ngân sách quảng cáo theo yêu cầu) đều được thông báo và thống nhất bằng văn bản trước khi thực hiện.',
      faq2: 'ZMarketing có cam kết KPI không?',
      faq2a: 'Có. Chúng tôi làm việc dựa trên số liệu thực tế. Các chỉ số KPI (Lượt tiếp cận, tương tác, chuyển đổi, doanh thu...) sẽ được cam kết rõ ràng trong hợp đồng dựa trên ngân sách và hiện trạng của doanh nghiệp.',
      faq3: 'Thời gian hợp đồng tối thiểu là bao lâu?',
      faq3a: 'Để đảm bảo hiệu quả của các chiến dịch Marketing (đặc biệt là SEO hay Branding), chúng tôi khuyến nghị thời gian hợp đồng tối thiểu từ 3 - 6 tháng. Tuy nhiên, chúng tôi cũng có các gói dùng thử hoặc ngắn hạn tùy nhu cầu.',
      faq4: 'Tôi có thể thay đổi gói dịch vụ giữa chừng không?',
      faq4a: 'Hoàn toàn có thể. Chúng tôi luôn linh hoạt điều chỉnh kế hoạch để phù hợp nhất với tình hình kinh doanh thực tế của khách hàng tại mỗi thời điểm.',
      // Work Process
      workingProcess: 'Quy Trình Làm Việc',
      step1: 'Tiếp nhận yêu cầu',
      step1Desc: 'Lắng nghe nhu cầu và mục tiêu của doanh nghiệp.',
      step2: 'Khảo sát & Phân tích',
      step2Desc: 'Nghiên cứu thị trường, đối thủ và nội tại doanh nghiệp.',
      step3: 'Đề xuất giải pháp',
      step3Desc: 'Lên kế hoạch chi tiết và tối ưu ngân sách.',
      step4: 'Ký kết & Triển khai',
      step4Desc: 'Cam kết KPI và báo cáo minh bạch theo tiến độ.',
      // Portfolio
      ourWork: 'Dự án của chúng tôi',
      featuredProjects: 'Dự án tiêu biểu',
      viewProject: 'Xem dự án',
      // Form Options
      jobOwner: 'Chủ doanh nghiệp / CEO',
      jobManager: 'Quản lý / Trưởng phòng',
      jobMarketer: 'Nhân viên Marketing',
      jobFreelancer: 'Freelancer',
      jobOther: 'Khác',
      subjMarketing: 'Marketing Tổng Thể',
      subjStrategy: 'Tư Vấn Chiến Lược',
      subjAds: 'Dịch Vụ Quảng Cáo (Facebook/Google/TikTok)',
      subjSEO: 'SEO Tổng Thể',
      subjTikTok: 'TikTok Marketing / Livestream',
      subjWeb: 'Thiết Kế Website',
      subjOther: 'Khác',
      budgetU20: 'Dưới 20 triệu',
      budget20_50: '20 - 50 triệu',
      budget50_100: '50 - 100 triệu',
      budgetO100: 'Trên 100 triệu',
      // Pricing Features (Startup)
      ftS1: 'Quản trị Fanpage: 8 bài viết/tháng',
      ftS2: 'Thiết kế hình ảnh cơ bản',
      ftS3: 'Setup quảng cáo Facebook cơ bản',
      ftS4: 'Báo cáo hiệu quả hằng tháng',
      ftS5: 'Hỗ trợ qua Zalo Group',
      // Pricing Features (Growth)
      ftG1: 'Quản trị Fanpage & Website: 15 bài/tháng',
      ftG2: 'Thiết kế hình ảnh & Video ngắn cơ bản',
      ftG3: 'Quảng cáo đa kênh (FB, Google) nâng cao',
      ftG4: 'Tối ưu SEO cơ bản',
      ftG5: 'Seeding hội nhóm & Forum',
      ftG6: 'Báo cáo tuần & tháng chi tiết',
      // Pricing Features (Enterprise)
      ftE1: 'Chiến lược Marketing tổng thể đa kênh',
      ftE2: 'Sản xuất TVC, Video Viral chuyên nghiệp',
      ftE3: 'Booking KOLs/Influencers',
      ftE4: 'Tổ chức sự kiện & Kích hoạt thương hiệu',
      ftE5: 'Quản trị khủng hoảng truyền thông',
      ftE6: 'Đội ngũ in-house dedicated riêng',
      // Why Choose Us
      wcuTitle: 'Tại sao chọn VIT DIGITAL?',
      wcuPartner: 'Đối Tác Tin Cậy Cho',
      wcuGrowth: 'Sự Tăng Trưởng',
      wcuDesc: 'Chúng tôi không chỉ là một đơn vị cung cấp dịch vụ, mà là người bạn đồng hành chiến lược, cùng bạn giải quyết bài toán doanh thu và thương hiệu.',
      wcuSecurity: 'Bảo Mật & An Toàn',
      wcuSecurityDesc: 'Cam kết bảo mật dữ liệu khách hàng tuyệt đối theo tiêu chuẩn quốc tế.',
      wcuKPI: 'Cam Kết KPI',
      wcuKPICommit: 'Hoàn tiền nếu không đạt hiệu quả cam kết.',
    }
  };

  const t = (key) => translations[language][key] || key;

  // Handle Theme Change
  useEffect(() => {
    const root = window.document.documentElement;
    if (theme === 'dark') {
      root.classList.add('dark');
    } else {
      root.classList.remove('dark');
    }
  }, [theme]);

  const toggleTheme = () => {
    setTheme(prev => prev === 'dark' ? 'light' : 'dark');
  };

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'vi' ? 'en' : 'vi');
  };

  return (
    <AppContext.Provider value={{ theme, toggleTheme, language, toggleLanguage, t }}>
      {children}
    </AppContext.Provider>
  );
};

export const useApp = () => useContext(AppContext);
